//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 10 19:04:17 CST 2022
//----------------------------------------------------

package simpl.parser;

/**
 * CUP generated interface containing symbol constants.
 */
public interface Symbols {
    /* terminals */
    int CONS = 37;
    int ORELSE = 24;
    int WITH = 6;
    int GE = 36;
    int UNIT = 38;
    int CASE = 15;
    int LPAREN = 46;
    int SEMI = 45;
    int INR = 43;
    int REF = 3;
    int RPAREN = 47;
    int REC = 5;
    int INL = 42;
    int NOT = 22;
    int LT = 33;
    int FN = 4;
    int NIL = 2;
    int IN = 9;
    int OR = 17;
    int COMMA = 44;
    int LAZY = 11;
    int DIV = 28;
    int NUM = 49;
    int LAZYFN = 7;
    int ASSIGN = 40;
    int IF = 12;
    int ID = 50;
    int LE = 34;
    int OF = 16;
    int EOF = 0;
    int APP = 48;
    int TRUE = 20;
    int error = 1;
    int MUL = 27;
    int ADD = 25;
    int MOD = 29;
    int EQ = 31;
    int ARROW = 39;
    int NEG = 30;
    int ELSE = 14;
    int ANDALSO = 23;
    int WHILE = 18;
    int LET = 8;
    int THEN = 13;
    int NE = 32;
    int END = 10;
    int FALSE = 21;
    int GT = 35;
    int SUB = 26;
    int DEREF = 41;
    int DO = 19;
}

